# Generated by Django 6.0.2 on 2026-03-06 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cible',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=255, unique=True)),
                ('type_cible', models.CharField(choices=[('ip', 'IP'), ('domaine', 'Domaine')], default='ip', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cible',
                'ordering': ['adresse'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('complete', 'Complete'), ('echoue', 'Echoue')], default='en_attente', max_length=20)),
                ('ports_scannes', models.PositiveIntegerField(default=65535)),
                ('ports_ouverts', models.PositiveIntegerField(default=0)),
                ('version_scanner', models.CharField(default='UltimaScanner', max_length=50)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='app_core.cible')),
            ],
            options={
                'db_table': 'scan',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('port', models.PositiveIntegerField()),
                ('protocole', models.CharField(default='tcp', max_length=10)),
                ('nom_service', models.CharField(default='unknown', max_length=100)),
                ('produit', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('banniere', models.TextField(blank=True, null=True)),
                ('en_tetes', models.JSONField(blank=True, default=dict)),
                ('etat', models.CharField(default='open', max_length=20)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app_core.scan')),
            ],
            options={
                'db_table': 'service',
                'ordering': ['port'],
                'unique_together': {('scan', 'port', 'protocole')},
            },
        ),
    ]
