# Generated by Django 6.0.2 on 2026-03-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='version_scanner',
            field=models.CharField(default='SocketScanner', max_length=50),
        ),
    ]
