# Generated by Django 6.0.2 on 2026-03-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_alter_scan_version_scanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_installed', models.BooleanField(default=False)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('site_name', models.CharField(blank=True, default='CVEye', max_length=150)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Installation Configuration',
                'verbose_name_plural': 'Installation Configuration',
                'db_table': 'installation_config',
            },
        ),
    ]
