# Generated by Django 6.0.2 on 2026-03-31 12:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_cible_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cible',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='cible',
            constraint=models.UniqueConstraint(fields=('owner', 'adresse'), name='unique_target_per_user'),
        ),
    ]
