# Generated by Django 6.0.2 on 2026-04-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0009_alter_cible_adresse_cible_unique_target_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cible',
            name='dernier_scan_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cible',
            name='periodicite_scan',
            field=models.CharField(blank=True, choices=[('toutes_les_heures', 'Toutes les heures'), ('tous_les_jours', 'Tous les jours'), ('toutes_les_semaines', 'Toutes les semaines'), ('tous_les_mois', 'Tous les mois')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cible',
            name='prochain_scan_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cible',
            name='surveillance_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='server_hs',
            field=models.BooleanField(default=False),
        ),
    ]
