# Generated by Django 6.0.2 on 2026-04-15 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0010_cible_dernier_scan_le_cible_periodicite_scan_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE scan
                    ADD COLUMN IF NOT EXISTS ports_scannes_courant integer NOT NULL DEFAULT 0;
                    """,
                    reverse_sql="""
                    ALTER TABLE scan
                    DROP COLUMN IF EXISTS ports_scannes_courant;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='scan',
                    name='ports_scannes_courant',
                    field=models.PositiveIntegerField(default=0),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='cible',
            name='adresse',
            field=models.CharField(max_length=80),
        ),
    ]
