from django.urls import path
from .views import (
    admin_console_view,
    approve_user_view,
    toggle_user_active_view,
    dashboard_view,
    targets_page_view,
    target_detail_view,
    scans_page_view,
    unban_ip_view,
    vulnerabilities_page_view,
    launch_target_scan_async_view,
    launch_target_port_scan_async_view,
    scan_details_view,
    scan_progress_view,
    edit_target_view,
    delete_target_view,
    target_report_options_view,
    download_target_report_pdf_view,
    vulnerability_search_view,
)

urlpatterns = [
    path("admin/console/", admin_console_view, name="admin_console"),
    path("admin/users/<int:user_id>/approve/", approve_user_view, name="approve_user"),
    path("admin/users/<int:user_id>/toggle-active/", toggle_user_active_view, name="toggle_user_active"),
    path("admin/banned-ips/<int:ban_id>/delete/", unban_ip_view, name="unban_ip"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("targets/", targets_page_view, name="targets"),
    path("targets/<uuid:target_id>/", target_detail_view, name="target_detail"),
    path("targets/<uuid:target_id>/report/", target_report_options_view, name="target_report_options"),
    path("targets/<uuid:target_id>/report.pdf", download_target_report_pdf_view, name="download_target_report_pdf"),
    path("targets/<uuid:target_id>/scan/async/", launch_target_scan_async_view, name="launch_target_scan_async"),
    path("targets/<uuid:target_id>/scan/ports/<int:port>/async/", launch_target_port_scan_async_view, name="launch_target_port_scan_async"),
    path("targets/<uuid:target_id>/edit/", edit_target_view, name="edit_target"),
    path("targets/<uuid:target_id>/delete/", delete_target_view, name="delete_target"),
    path("scans/", scans_page_view, name="scans"),
    path("scans/progress/", scan_progress_view, name="scan_progress"),
    path("scans/<uuid:scan_id>/details/", scan_details_view, name="scan_details"),
    path("vulnerabilities/", vulnerabilities_page_view, name="vulnerabilities"),
    path("vulnerabilities/search/", vulnerability_search_view, name="vulnerabilities_search"),
]
